apiVersion: v1
kind: Service
metadata:
  name: movies-backend-service
  labels:
    app: movies-backend-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: movies-backend