apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    run: backend
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080
    protocol: TCP
  selector:
    app: webserver
