apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: database-service
  labels:
    kubernetes.io/service-name: database-service
addressType: IPv4
ports:
  - name: '' 
    appProtocol: http
    protocol: TCP
    port: 5432
endpoints:
  - addresses:
      - "172.19.0.2"