apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-v1-backend-deployment
  labels:
    app: movies-v1-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movies-v1-backend
  template:
    metadata:
      labels:
        app: movies-v1-backend
    spec:
      restartPolicy: Always
      containers:
        - name: movies-v1-backend
          image: movies:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
