apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-volume-claim
  labels:
    app: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath