version: "3.3"
services:
  database:
    container_name: database
    build:
      context: ./image
    ports:
      - 5432:5432
    env_file:
      - ./database.env
    volumes:
      - type: volume
        source: database-vol
        target: /var/lib/postgresql/data 
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 4s

volumes:
  database-vol: 
    name: database-vol
